# Generated by Django 3.1.1 on 2025-03-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fcm_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='reply',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
        migrations.CreateModel(
            name='HolisticEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_solving_skills', models.IntegerField(default=0, help_text='Score out of 10')),
                ('integrity', models.IntegerField(default=0, help_text='Score out of 10')),
                ('leadership', models.IntegerField(default=0, help_text='Score out of 10')),
                ('discipline', models.IntegerField(default=0, help_text='Score out of 10')),
                ('collaboration', models.IntegerField(default=0, help_text='Score out of 10')),
                ('extra_curricular_activities', models.IntegerField(default=0, help_text='Score out of 10')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.session')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
            options={
                'unique_together': {('student', 'staff', 'session')},
            },
        ),
    ]
